// Code generated by jk generate all -t OrderService; DO NOT EDIT.

package order

import (
	"context"
	"github.com/go-kit/kit/endpoint"
)

func makeEndpointFromFunc[REQ, RESP any](f func(context.Context, REQ) (RESP, error)) endpoint.Endpoint {
	return func(ctx context.Context, r interface{}) (interface{}, error) {
		req := r.(REQ)
		return f(ctx, req)
	}
}

type EndpointSet struct {
	CancelOrderEndpoint    endpoint.Endpoint
	CreateOrderEndpoint    endpoint.Endpoint
	GetOrderDetailEndpoint endpoint.Endpoint
}

func (o EndpointSet) CancelOrder(ctx context.Context, req CancelOrderRequest) (arg0 CancelOrderResponse, arg1 error) {
	resp, err := o.CancelOrderEndpoint(ctx, req)
	return resp.(CancelOrderResponse), err
}

func (o EndpointSet) CreateOrder(ctx context.Context, req CreateOrderRequest) (arg0 CreateOrderResponse, arg1 error) {
	resp, err := o.CreateOrderEndpoint(ctx, req)
	return resp.(CreateOrderResponse), err
}

func (o EndpointSet) GetOrderDetail(ctx context.Context, req GetOrderDetailRequest) (arg0 GetOrderDetailResponse, arg1 error) {
	resp, err := o.GetOrderDetailEndpoint(ctx, req)
	return resp.(GetOrderDetailResponse), err
}

func NewEndpointSet(svc OrderService) EndpointSet {
	return EndpointSet{
		CancelOrderEndpoint:    makeEndpointFromFunc(svc.CancelOrder),
		CreateOrderEndpoint:    makeEndpointFromFunc(svc.CreateOrder),
		GetOrderDetailEndpoint: makeEndpointFromFunc(svc.GetOrderDetail),
	}
}

func (s EndpointSet) With(outer endpoint.Middleware, others ...endpoint.Middleware) EndpointSet {
	return EndpointSet{
		CancelOrderEndpoint:    endpoint.Chain(outer, others...)(s.CancelOrderEndpoint),
		CreateOrderEndpoint:    endpoint.Chain(outer, others...)(s.CreateOrderEndpoint),
		GetOrderDetailEndpoint: endpoint.Chain(outer, others...)(s.GetOrderDetailEndpoint),
	}
}
