// Code generated by jk generate all -t OrderService; DO NOT EDIT.

package order

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"
	khttp "github.com/go-kit/kit/transport/http"
	httprouter "github.com/julienschmidt/httprouter"
	httpSwagger "github.com/swaggo/http-swagger/v2"
	"net/http"
	"net/url"
)

func httpJSONRequestDecoder[T any](ctx context.Context, req *http.Request) (any, error) {
	var request T
	err := json.NewDecoder(req.Body).Decode(&request)
	if err != nil {
		return nil, err
	}
	return request, nil
}

func httpJSONResponseDecoder[T any](ctx context.Context, resp *http.Response) (any, error) {
	var response T
	defer resp.Body.Close()
	err := json.NewDecoder(resp.Body).Decode(&response)
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:embed swagger.json
var swagger embed.FS

type HTTPClientSet struct {
	CancelOrderClient    *khttp.Client
	CreateOrderClient    *khttp.Client
	GetOrderDetailClient *khttp.Client
}

func NewHTTPClientSet(scheme, host string, port int, options ...khttp.ClientOption) HTTPClientSet {
	return HTTPClientSet{
		CancelOrderClient: khttp.NewClient(
			http.MethodPost,
			&url.URL{
				Host:   fmt.Sprintf("%s:%d", host, port),
				Path:   "/api/v1/order-service/cancel-order",
				Scheme: scheme,
			},
			khttp.EncodeJSONRequest,
			httpJSONResponseDecoder[CancelOrderResponse],
			options...),
		CreateOrderClient: khttp.NewClient(
			http.MethodPost,
			&url.URL{
				Host:   fmt.Sprintf("%s:%d", host, port),
				Path:   "/api/v1/order-service/create-order",
				Scheme: scheme,
			},
			khttp.EncodeJSONRequest,
			httpJSONResponseDecoder[CreateOrderResponse],
			options...),
		GetOrderDetailClient: khttp.NewClient(
			http.MethodPost,
			&url.URL{
				Host:   fmt.Sprintf("%s:%d", host, port),
				Path:   "/api/v1/order-service/get-order-detail",
				Scheme: scheme,
			},
			khttp.EncodeJSONRequest,
			httpJSONResponseDecoder[GetOrderDetailResponse],
			options...),
	}
}

func (s HTTPClientSet) EndpointSet() EndpointSet {
	return EndpointSet{
		CancelOrderEndpoint:    s.CancelOrderClient.Endpoint(),
		CreateOrderEndpoint:    s.CreateOrderClient.Endpoint(),
		GetOrderDetailEndpoint: s.GetOrderDetailClient.Endpoint(),
	}
}

type HTTPServerSet struct {
	CancelOrderServer    *khttp.Server
	CreateOrderServer    *khttp.Server
	GetOrderDetailServer *khttp.Server
}

func NewHTTPServerSet(endpointSet EndpointSet, options ...khttp.ServerOption) HTTPServerSet {
	return HTTPServerSet{
		CancelOrderServer: khttp.NewServer(
			endpointSet.CancelOrderEndpoint,
			httpJSONRequestDecoder[CancelOrderRequest],
			khttp.EncodeJSONResponse,
			append(options, khttp.ServerBefore(khttp.PopulateRequestContext))...),
		CreateOrderServer: khttp.NewServer(
			endpointSet.CreateOrderEndpoint,
			httpJSONRequestDecoder[CreateOrderRequest],
			khttp.EncodeJSONResponse,
			append(options, khttp.ServerBefore(khttp.PopulateRequestContext))...),
		GetOrderDetailServer: khttp.NewServer(
			endpointSet.GetOrderDetailEndpoint,
			httpJSONRequestDecoder[GetOrderDetailRequest],
			khttp.EncodeJSONResponse,
			append(options, khttp.ServerBefore(khttp.PopulateRequestContext))...),
	}
}

func (s HTTPServerSet) Handler() http.Handler {
	var m = new(httprouter.Router)
	m.Handler(
		http.MethodGet,
		"/swagger/order-service/spec/*rest",
		http.StripPrefix("/swagger/order-service/spec/", http.FileServer(http.FS(swagger))))
	m.Handler(
		http.MethodGet,
		"/swagger/order-service/swagger-ui/*rest",
		httpSwagger.Handler(httpSwagger.URL("/swagger/order-service/spec/swagger.json")))
	m.Handler(
		http.MethodPost,
		"/api/v1/order-service/cancel-order",
		s.CancelOrderServer)
	m.Handler(
		http.MethodPost,
		"/api/v1/order-service/create-order",
		s.CreateOrderServer)
	m.Handler(
		http.MethodPost,
		"/api/v1/order-service/get-order-detail",
		s.GetOrderDetailServer)
	return m
}
