/*
Copyright © 2023 weak_ptr <weak_ptr@outlook.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

package cmd

import (
	"fmt"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"log"
	"os"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/nnnewb/battery/maps"
	"github.com/nnnewb/jk/internal/domain"
	"github.com/nnnewb/jk/internal/gen"
	"github.com/nnnewb/jk/internal/utils"
	"github.com/spf13/cobra"
)

// allCmd represents the all command
var allCmd = &cobra.Command{
	Use:   "all",
	Short: "Generate all we can.",
	Long:  `Generate all we can.`,
	Run: func(cmd *cobra.Command, args []string) {
		wd, err := os.Getwd()
		cobra.CheckErr(err)

		pkgPath, err := cmd.Flags().GetString("package")
		cobra.CheckErr(err)

		if pkgPath == "" {
			pkgPath, err = utils.ResolveFullPackagePath(wd, wd)
			if err != nil {
				log.Fatalf("can not resolve full path of current working directory %s, error %+v", wd, err)
			}
		}

		typeName, err := cmd.Flags().GetString("typename")
		cobra.CheckErr(err)

		fset := token.NewFileSet()
		pkgs, err := parser.ParseDir(fset, wd, nil, parser.ParseComments)
		cobra.CheckErr(err)

		var astPkg *ast.Package
		for name, p := range pkgs {
			if strings.Contains(name, "_test") {
				continue
			}
			astPkg = p
		}

		if astPkg == nil || astPkg.Files == nil {
			log.Fatalf("no valid package found in path %s, test package skipped", wd)
			return
		}

		info := &types.Info{}
		typeCheckerConfig := types.Config{Importer: importer.ForCompiler(fset, "source", nil)}
		pkg, err := typeCheckerConfig.Check(pkgPath, fset, maps.Values(astPkg.Files), info)
		cobra.CheckErr(err)

		service, err := domain.ParseInterfaceData(pkg, astPkg, typeName)
		cobra.CheckErr(err)

		f := jen.NewFilePath(pkgPath)
		f.HeaderComment(fmt.Sprintf("Code generated by jk %s; DO NOT EDIT.", strings.Join(os.Args[1:], " ")))
		utils.InitializeFileCommon(f)
		err = gen.GenerateEndpoints(f, service.Interface)
		if err != nil {
			log.Fatalf("generate endpoints for service failed, error %+v", err)
		}

		err = f.Save("endpoint_gen.go")
		if err != nil {
			log.Fatalf("render generated service layer code failed, error %+v", err)
		}

		f = jen.NewFilePath(pkgPath)
		f.HeaderComment(fmt.Sprintf("Code generated by jk %s; DO NOT EDIT.", strings.Join(os.Args[1:], " ")))
		utils.InitializeFileCommon(f)
		gen.GenerateHTTPTransport(f, service)

		err = f.Save("transport_gen.go")
		if err != nil {
			log.Fatalf("render generated transport layer code failed, error %+v", err)
		}

		file, err := os.OpenFile("swagger.json", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
		if err != nil {
			log.Fatalf("open file failed, error %+v", err)
		}

		err = gen.GenerateSwagger(file, service)
		if err != nil {
			log.Fatalf("generate swagger failed, error %+v", err)
		}

		file, err = os.OpenFile("api.mjs", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
		if err != nil {
			log.Fatalf("open file failed, error %+v", err)
		}

		_, err = fmt.Fprintf(file, "// Code generated by jk %s; DO NOT EDIT.\n", strings.Join(os.Args[1:], " "))
		if err != nil {
			log.Fatalf("write javascript api client failed, error %+v", err)
		}

		err = gen.GenerateJavascriptClient(file, service)
		if err != nil {
			log.Fatalf("generate javascript api client failed, error %+v", err)
		}
	},
}

func init() {
	generateCmd.AddCommand(allCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// allCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// allCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
