// This file is generated by jk, DO NOT EDIT.

package grpc

import endpoint "stringsvc/service/endpoint"

// EncodeBuyRequest encode endpoint request struct to gRPC message struct.
func EncodeBuyRequest(req endpoint.BuyRequest) (BuyRequest, error) {
	ret := &BuyRequest{}
	ret.Good = &Good{}
	ret.Good.Name = req.Good.Name
	ret.Good.Price = req.Good.Price
	return ret, nil
}

// EncodeJoinRequest encode endpoint request struct to gRPC message struct.
func EncodeJoinRequest(req endpoint.JoinRequest) (JoinRequest, error) {
	ret := &JoinRequest{}
	ret.Parts = req.Parts
	return ret, nil
}

// EncodeJoin2Request encode endpoint request struct to gRPC message struct.
func EncodeJoin2Request(req endpoint.Join2Request) (Join2Request, error) {
	ret := &Join2Request{}
	ret.Parts = req.Parts
	return ret, nil
}

// EncodeLowercaseRequest encode endpoint request struct to gRPC message struct.
func EncodeLowercaseRequest(req endpoint.LowercaseRequest) (LowercaseRequest, error) {
	ret := &LowercaseRequest{}
	ret.Name = req.Name
	ret.Name2 = req.Name2
	return ret, nil
}

// EncodeUppercaseRequest encode endpoint request struct to gRPC message struct.
func EncodeUppercaseRequest(req endpoint.UppercaseRequest) (UppercaseRequest, error) {
	ret := &UppercaseRequest{}
	ret.Name = req.Name
	ret.Name2 = req.Name2
	return ret, nil
}
