// This file is generated by jk, DO NOT EDIT.

package endpoint

import (
	"context"
	endpoint "github.com/go-kit/kit/endpoint"
	service "stringsvc/service"
)

type BuyRequest struct {
	Good service.Good
}

type BuyResponse struct {
	OrderID string
}

func makeBuyEndpoint(svc service.Service) endpoint.Endpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		request := req.(*BuyRequest)
		orderID, err := svc.Buy(ctx, request.Good)
		if err != nil {
			return nil, err
		}
		resp := &BuyResponse{OrderID: orderID}
		return resp, nil
	}
}

type JoinRequest struct {
	Parts []string
}

type JoinResponse struct {
	Text string
}

func makeJoinEndpoint(svc service.Service) endpoint.Endpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		request := req.(*JoinRequest)
		text, err := svc.Join(ctx, request.Parts)
		if err != nil {
			return nil, err
		}
		resp := &JoinResponse{Text: text}
		return resp, nil
	}
}

type Join2Request struct {
	Parts map[string]string
}

type Join2Response struct {
	Text string
}

func makeJoin2Endpoint(svc service.Service) endpoint.Endpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		request := req.(*Join2Request)
		text, err := svc.Join2(ctx, request.Parts)
		if err != nil {
			return nil, err
		}
		resp := &Join2Response{Text: text}
		return resp, nil
	}
}

type LowercaseRequest struct {
	Name  string
	Name2 string
}

type LowercaseResponse struct {
	Text string
}

func makeLowercaseEndpoint(svc service.Service) endpoint.Endpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		request := req.(*LowercaseRequest)
		text, err := svc.Lowercase(ctx, request.Name, request.Name2)
		if err != nil {
			return nil, err
		}
		resp := &LowercaseResponse{Text: text}
		return resp, nil
	}
}

type UppercaseRequest struct {
	Name  string
	Name2 string
}

type UppercaseResponse struct {
	Text string
}

func makeUppercaseEndpoint(svc service.Service) endpoint.Endpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		request := req.(*UppercaseRequest)
		text, err := svc.Uppercase(ctx, request.Name, request.Name2)
		if err != nil {
			return nil, err
		}
		resp := &UppercaseResponse{Text: text}
		return resp, nil
	}
}
